### ISSUE TITLE
Dead loop test case

### ISSUE THREAD

**Issue by sunfmin** [lrstanley/go-queryparser#1]
```go
		{name: "Just two filter", args: args{raw: "batch:125 ok:1", allowed: []string{"batch"}}, wantQry: Query{
			Orig:   "batch:125 ok:1",
			Raw:    "",
			Pretty: "batch:125 ok:1",
			filters: map[string][]string{
				"batch": {"125"},
				"ok":    {"1"},
			},
		}},

```

```go
allowed: []string{"batch"}
```
This allowed parameter seems caused dead loop

@lrstanley

**Comment by lrstanley** [comment]
This does look to be a bug. Taking a look now.

**Comment by lrstanley** [comment]
Let me know if you are still experiencing issues after the latest push. The specific test case you provided is invalid (it would fail due to filters only being filled with `allowed` filters), but I've added a test which should cover the actual problem.
